// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.IMEIGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("brand")]
        public string Brand { get; set; }

        [JsonProperty("imeis")]
        public Imei[] Imeis { get; set; }
    }

    public partial class Imei
    {
        [JsonProperty("imei")]
        public string ImeiImei { get; set; }

        [JsonProperty("tac")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Tac { get; set; }

        [JsonProperty("manufacturer")]
        public string Manufacturer { get; set; }

        [JsonProperty("model")]
        public string Model { get; set; }

        [JsonProperty("serial")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Serial { get; set; }

        [JsonProperty("checksum")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Checksum { get; set; }

        [JsonProperty("isValid")]
        public bool IsValid { get; set; }
    }
}
